name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.x'
    - name: Install backend dependencies
      run: cd backend && npm install
    - name: Run backend tests
      env:
        MONGO_URI_TEST: ${{ secrets.MONGO_URI_TEST }} # Maps the secret to the variable the app expects
        MONGO_URI: ${{ secrets.MONGO_URI }} # Maps the secret to the variable the app expects
      run: cd backend && npm test
    - name: Install frontend dependencies
      run: cd frontend && npm install
    - name: Build frontend
      run: cd frontend && npm run build